lint:
  template_strings: false

nf_core_version: 3.2.1
repository_type: pipeline

template:
  author: Anna Delgado
  description: Multi-platform pipeline for unified processing of single-cell and single-nucleus long-read RNA-seq data
  force: false
  is_nfcore: false
  name: sclr-multi
  org: biocorecrg
  outdir: .
  version: 1.0.0
  
  
