name: Bug report
description: Report something that is broken or incorrect
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before posting an issue, please check the scLR-multi documentation and existing issues.

  - type: textarea
    attributes:
      label: Description of the bug
      description: A clear and concise description of the problem.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Command used and terminal output
      description: Please provide the command used to launch the pipeline and the relevant terminal output.
      render: console

  - type: textarea
    attributes:
      label: Relevant files
      description: |
        Please attach any relevant files. The `.nextflow.log` file is often useful, as well as custom Nextflow configuration files.

  - type: textarea
    attributes:
      label: System information
      description: |
        - scLR-multi version:
        - Nextflow version:
        - Hardware (e.g. HPC, Desktop, Cloud):
        - Executor (e.g. slurm, local, awsbatch):
        - Container engine (e.g. Docker, Singularity, Apptainer):
        - Operating system:
    validations:
      required: true
